// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CoinGasColumns holds the columns for the "coin_gas" table.
	CoinGasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// CoinGasTable holds the schema information for the "coin_gas" table.
	CoinGasTable = &schema.Table{
		Name:       "coin_gas",
		Columns:    CoinGasColumns,
		PrimaryKey: []*schema.Column{CoinGasColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CoinGasTable,
	}
)

func init() {
}
