// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/gas-feeder/pkg/db/ent/coingas"
)

// CoinGas is the model entity for the CoinGas schema.
type CoinGas struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CoinGas) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case coingas.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type CoinGas", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CoinGas fields.
func (cg *CoinGas) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case coingas.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cg.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this CoinGas.
// Note that you need to call CoinGas.Unwrap() before calling this method if this CoinGas
// was returned from a transaction, and the transaction was committed or rolled back.
func (cg *CoinGas) Update() *CoinGasUpdateOne {
	return (&CoinGasClient{config: cg.config}).UpdateOne(cg)
}

// Unwrap unwraps the CoinGas entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cg *CoinGas) Unwrap() *CoinGas {
	tx, ok := cg.config.driver.(*txDriver)
	if !ok {
		panic("ent: CoinGas is not a transactional entity")
	}
	cg.config.driver = tx.drv
	return cg
}

// String implements the fmt.Stringer.
func (cg *CoinGas) String() string {
	var builder strings.Builder
	builder.WriteString("CoinGas(")
	builder.WriteString(fmt.Sprintf("id=%v", cg.ID))
	builder.WriteByte(')')
	return builder.String()
}

// CoinGasSlice is a parsable slice of CoinGas.
type CoinGasSlice []*CoinGas

func (cg CoinGasSlice) config(cfg config) {
	for _i := range cg {
		cg[_i].config = cfg
	}
}
