// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/gas-feeder/pkg/db/ent/coingas"
	"github.com/NpoolPlatform/gas-feeder/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// CoinGasQuery is the builder for querying CoinGas entities.
type CoinGasQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.CoinGas
	modifiers  []func(s *sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CoinGasQuery builder.
func (cgq *CoinGasQuery) Where(ps ...predicate.CoinGas) *CoinGasQuery {
	cgq.predicates = append(cgq.predicates, ps...)
	return cgq
}

// Limit adds a limit step to the query.
func (cgq *CoinGasQuery) Limit(limit int) *CoinGasQuery {
	cgq.limit = &limit
	return cgq
}

// Offset adds an offset step to the query.
func (cgq *CoinGasQuery) Offset(offset int) *CoinGasQuery {
	cgq.offset = &offset
	return cgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cgq *CoinGasQuery) Unique(unique bool) *CoinGasQuery {
	cgq.unique = &unique
	return cgq
}

// Order adds an order step to the query.
func (cgq *CoinGasQuery) Order(o ...OrderFunc) *CoinGasQuery {
	cgq.order = append(cgq.order, o...)
	return cgq
}

// First returns the first CoinGas entity from the query.
// Returns a *NotFoundError when no CoinGas was found.
func (cgq *CoinGasQuery) First(ctx context.Context) (*CoinGas, error) {
	nodes, err := cgq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{coingas.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cgq *CoinGasQuery) FirstX(ctx context.Context) *CoinGas {
	node, err := cgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CoinGas ID from the query.
// Returns a *NotFoundError when no CoinGas ID was found.
func (cgq *CoinGasQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cgq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{coingas.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cgq *CoinGasQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := cgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CoinGas entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CoinGas entity is found.
// Returns a *NotFoundError when no CoinGas entities are found.
func (cgq *CoinGasQuery) Only(ctx context.Context) (*CoinGas, error) {
	nodes, err := cgq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{coingas.Label}
	default:
		return nil, &NotSingularError{coingas.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cgq *CoinGasQuery) OnlyX(ctx context.Context) *CoinGas {
	node, err := cgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CoinGas ID in the query.
// Returns a *NotSingularError when more than one CoinGas ID is found.
// Returns a *NotFoundError when no entities are found.
func (cgq *CoinGasQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cgq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{coingas.Label}
	default:
		err = &NotSingularError{coingas.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cgq *CoinGasQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := cgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CoinGasSlice.
func (cgq *CoinGasQuery) All(ctx context.Context) ([]*CoinGas, error) {
	if err := cgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return cgq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (cgq *CoinGasQuery) AllX(ctx context.Context) []*CoinGas {
	nodes, err := cgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CoinGas IDs.
func (cgq *CoinGasQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := cgq.Select(coingas.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cgq *CoinGasQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := cgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cgq *CoinGasQuery) Count(ctx context.Context) (int, error) {
	if err := cgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return cgq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (cgq *CoinGasQuery) CountX(ctx context.Context) int {
	count, err := cgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cgq *CoinGasQuery) Exist(ctx context.Context) (bool, error) {
	if err := cgq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return cgq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (cgq *CoinGasQuery) ExistX(ctx context.Context) bool {
	exist, err := cgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CoinGasQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cgq *CoinGasQuery) Clone() *CoinGasQuery {
	if cgq == nil {
		return nil
	}
	return &CoinGasQuery{
		config:     cgq.config,
		limit:      cgq.limit,
		offset:     cgq.offset,
		order:      append([]OrderFunc{}, cgq.order...),
		predicates: append([]predicate.CoinGas{}, cgq.predicates...),
		// clone intermediate query.
		sql:    cgq.sql.Clone(),
		path:   cgq.path,
		unique: cgq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CoinGas.Query().
//		GroupBy(coingas.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (cgq *CoinGasQuery) GroupBy(field string, fields ...string) *CoinGasGroupBy {
	group := &CoinGasGroupBy{config: cgq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := cgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return cgq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.CoinGas.Query().
//		Select(coingas.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (cgq *CoinGasQuery) Select(fields ...string) *CoinGasSelect {
	cgq.fields = append(cgq.fields, fields...)
	return &CoinGasSelect{CoinGasQuery: cgq}
}

func (cgq *CoinGasQuery) prepareQuery(ctx context.Context) error {
	for _, f := range cgq.fields {
		if !coingas.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cgq.path != nil {
		prev, err := cgq.path(ctx)
		if err != nil {
			return err
		}
		cgq.sql = prev
	}
	if coingas.Policy == nil {
		return errors.New("ent: uninitialized coingas.Policy (forgotten import ent/runtime?)")
	}
	if err := coingas.Policy.EvalQuery(ctx, cgq); err != nil {
		return err
	}
	return nil
}

func (cgq *CoinGasQuery) sqlAll(ctx context.Context) ([]*CoinGas, error) {
	var (
		nodes = []*CoinGas{}
		_spec = cgq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &CoinGas{config: cgq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if len(cgq.modifiers) > 0 {
		_spec.Modifiers = cgq.modifiers
	}
	if err := sqlgraph.QueryNodes(ctx, cgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cgq *CoinGasQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cgq.querySpec()
	if len(cgq.modifiers) > 0 {
		_spec.Modifiers = cgq.modifiers
	}
	_spec.Node.Columns = cgq.fields
	if len(cgq.fields) > 0 {
		_spec.Unique = cgq.unique != nil && *cgq.unique
	}
	return sqlgraph.CountNodes(ctx, cgq.driver, _spec)
}

func (cgq *CoinGasQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := cgq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (cgq *CoinGasQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   coingas.Table,
			Columns: coingas.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: coingas.FieldID,
			},
		},
		From:   cgq.sql,
		Unique: true,
	}
	if unique := cgq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := cgq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coingas.FieldID)
		for i := range fields {
			if fields[i] != coingas.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cgq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cgq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cgq *CoinGasQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cgq.driver.Dialect())
	t1 := builder.Table(coingas.Table)
	columns := cgq.fields
	if len(columns) == 0 {
		columns = coingas.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cgq.sql != nil {
		selector = cgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cgq.unique != nil && *cgq.unique {
		selector.Distinct()
	}
	for _, m := range cgq.modifiers {
		m(selector)
	}
	for _, p := range cgq.predicates {
		p(selector)
	}
	for _, p := range cgq.order {
		p(selector)
	}
	if offset := cgq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cgq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (cgq *CoinGasQuery) ForUpdate(opts ...sql.LockOption) *CoinGasQuery {
	if cgq.driver.Dialect() == dialect.Postgres {
		cgq.Unique(false)
	}
	cgq.modifiers = append(cgq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return cgq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (cgq *CoinGasQuery) ForShare(opts ...sql.LockOption) *CoinGasQuery {
	if cgq.driver.Dialect() == dialect.Postgres {
		cgq.Unique(false)
	}
	cgq.modifiers = append(cgq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return cgq
}

// CoinGasGroupBy is the group-by builder for CoinGas entities.
type CoinGasGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cggb *CoinGasGroupBy) Aggregate(fns ...AggregateFunc) *CoinGasGroupBy {
	cggb.fns = append(cggb.fns, fns...)
	return cggb
}

// Scan applies the group-by query and scans the result into the given value.
func (cggb *CoinGasGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := cggb.path(ctx)
	if err != nil {
		return err
	}
	cggb.sql = query
	return cggb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (cggb *CoinGasGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := cggb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (cggb *CoinGasGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(cggb.fields) > 1 {
		return nil, errors.New("ent: CoinGasGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := cggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (cggb *CoinGasGroupBy) StringsX(ctx context.Context) []string {
	v, err := cggb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cggb *CoinGasGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = cggb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coingas.Label}
	default:
		err = fmt.Errorf("ent: CoinGasGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (cggb *CoinGasGroupBy) StringX(ctx context.Context) string {
	v, err := cggb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (cggb *CoinGasGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(cggb.fields) > 1 {
		return nil, errors.New("ent: CoinGasGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := cggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (cggb *CoinGasGroupBy) IntsX(ctx context.Context) []int {
	v, err := cggb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cggb *CoinGasGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = cggb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coingas.Label}
	default:
		err = fmt.Errorf("ent: CoinGasGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (cggb *CoinGasGroupBy) IntX(ctx context.Context) int {
	v, err := cggb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (cggb *CoinGasGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(cggb.fields) > 1 {
		return nil, errors.New("ent: CoinGasGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := cggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (cggb *CoinGasGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := cggb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cggb *CoinGasGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = cggb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coingas.Label}
	default:
		err = fmt.Errorf("ent: CoinGasGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (cggb *CoinGasGroupBy) Float64X(ctx context.Context) float64 {
	v, err := cggb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (cggb *CoinGasGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(cggb.fields) > 1 {
		return nil, errors.New("ent: CoinGasGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := cggb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (cggb *CoinGasGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := cggb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cggb *CoinGasGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = cggb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coingas.Label}
	default:
		err = fmt.Errorf("ent: CoinGasGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (cggb *CoinGasGroupBy) BoolX(ctx context.Context) bool {
	v, err := cggb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cggb *CoinGasGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range cggb.fields {
		if !coingas.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := cggb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cggb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (cggb *CoinGasGroupBy) sqlQuery() *sql.Selector {
	selector := cggb.sql.Select()
	aggregation := make([]string, 0, len(cggb.fns))
	for _, fn := range cggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(cggb.fields)+len(cggb.fns))
		for _, f := range cggb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(cggb.fields...)...)
}

// CoinGasSelect is the builder for selecting fields of CoinGas entities.
type CoinGasSelect struct {
	*CoinGasQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (cgs *CoinGasSelect) Scan(ctx context.Context, v interface{}) error {
	if err := cgs.prepareQuery(ctx); err != nil {
		return err
	}
	cgs.sql = cgs.CoinGasQuery.sqlQuery(ctx)
	return cgs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (cgs *CoinGasSelect) ScanX(ctx context.Context, v interface{}) {
	if err := cgs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (cgs *CoinGasSelect) Strings(ctx context.Context) ([]string, error) {
	if len(cgs.fields) > 1 {
		return nil, errors.New("ent: CoinGasSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := cgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (cgs *CoinGasSelect) StringsX(ctx context.Context) []string {
	v, err := cgs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (cgs *CoinGasSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = cgs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coingas.Label}
	default:
		err = fmt.Errorf("ent: CoinGasSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (cgs *CoinGasSelect) StringX(ctx context.Context) string {
	v, err := cgs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (cgs *CoinGasSelect) Ints(ctx context.Context) ([]int, error) {
	if len(cgs.fields) > 1 {
		return nil, errors.New("ent: CoinGasSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := cgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (cgs *CoinGasSelect) IntsX(ctx context.Context) []int {
	v, err := cgs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (cgs *CoinGasSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = cgs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coingas.Label}
	default:
		err = fmt.Errorf("ent: CoinGasSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (cgs *CoinGasSelect) IntX(ctx context.Context) int {
	v, err := cgs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (cgs *CoinGasSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(cgs.fields) > 1 {
		return nil, errors.New("ent: CoinGasSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := cgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (cgs *CoinGasSelect) Float64sX(ctx context.Context) []float64 {
	v, err := cgs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (cgs *CoinGasSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = cgs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coingas.Label}
	default:
		err = fmt.Errorf("ent: CoinGasSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (cgs *CoinGasSelect) Float64X(ctx context.Context) float64 {
	v, err := cgs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (cgs *CoinGasSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(cgs.fields) > 1 {
		return nil, errors.New("ent: CoinGasSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := cgs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (cgs *CoinGasSelect) BoolsX(ctx context.Context) []bool {
	v, err := cgs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (cgs *CoinGasSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = cgs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{coingas.Label}
	default:
		err = fmt.Errorf("ent: CoinGasSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (cgs *CoinGasSelect) BoolX(ctx context.Context) bool {
	v, err := cgs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cgs *CoinGasSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := cgs.sql.Query()
	if err := cgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
