// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/gas-feeder/pkg/db/ent/coingas"
	"github.com/NpoolPlatform/gas-feeder/pkg/db/ent/predicate"
)

// CoinGasDelete is the builder for deleting a CoinGas entity.
type CoinGasDelete struct {
	config
	hooks    []Hook
	mutation *CoinGasMutation
}

// Where appends a list predicates to the CoinGasDelete builder.
func (cgd *CoinGasDelete) Where(ps ...predicate.CoinGas) *CoinGasDelete {
	cgd.mutation.Where(ps...)
	return cgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cgd *CoinGasDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cgd.hooks) == 0 {
		affected, err = cgd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CoinGasMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cgd.mutation = mutation
			affected, err = cgd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cgd.hooks) - 1; i >= 0; i-- {
			if cgd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cgd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cgd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (cgd *CoinGasDelete) ExecX(ctx context.Context) int {
	n, err := cgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cgd *CoinGasDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: coingas.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: coingas.FieldID,
			},
		},
	}
	if ps := cgd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, cgd.driver, _spec)
}

// CoinGasDeleteOne is the builder for deleting a single CoinGas entity.
type CoinGasDeleteOne struct {
	cgd *CoinGasDelete
}

// Exec executes the deletion query.
func (cgdo *CoinGasDeleteOne) Exec(ctx context.Context) error {
	n, err := cgdo.cgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{coingas.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cgdo *CoinGasDeleteOne) ExecX(ctx context.Context) {
	cgdo.cgd.ExecX(ctx)
}
