// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/NpoolPlatform/gas-feeder/pkg/db/ent/coingas"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 1)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   coingas.Table,
			Columns: coingas.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: coingas.FieldID,
			},
		},
		Type:   "CoinGas",
		Fields: map[string]*sqlgraph.FieldSpec{},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (cgq *CoinGasQuery) addPredicate(pred func(s *sql.Selector)) {
	cgq.predicates = append(cgq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the CoinGasQuery builder.
func (cgq *CoinGasQuery) Filter() *CoinGasFilter {
	return &CoinGasFilter{cgq}
}

// addPredicate implements the predicateAdder interface.
func (m *CoinGasMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the CoinGasMutation builder.
func (m *CoinGasMutation) Filter() *CoinGasFilter {
	return &CoinGasFilter{m}
}

// CoinGasFilter provides a generic filtering capability at runtime for CoinGasQuery.
type CoinGasFilter struct {
	predicateAdder
}

// Where applies the entql predicate on the query filter.
func (f *CoinGasFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int predicate on the id field.
func (f *CoinGasFilter) WhereID(p entql.IntP) {
	f.Where(p.Field(coingas.FieldID))
}
