// Code generated by entc, DO NOT EDIT.

//go:build tools
// +build tools

// Package internal holds a loadable version of the latest schema.
package internal

const Schema = `{"Schema":"github.com/NpoolPlatform/gas-feeder/pkg/db/ent/schema","Package":"github.com/NpoolPlatform/gas-feeder/pkg/db/ent","Schemas":[{"name":"CoinGas","config":{"Table":""}}],"Features":["entql","sql/lock","sql/upsert","privacy","schema/snapshot"]}`
