// Code generated by entc, DO NOT EDIT.

package coingas

import (
	"entgo.io/ent"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the coingas type in the database.
	Label = "coin_gas"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCoinTypeID holds the string denoting the coin_type_id field in the database.
	FieldCoinTypeID = "coin_type_id"
	// FieldGasCoinTypeID holds the string denoting the gas_coin_type_id field in the database.
	FieldGasCoinTypeID = "gas_coin_type_id"
	// FieldDepositThresholdLow holds the string denoting the deposit_threshold_low field in the database.
	FieldDepositThresholdLow = "deposit_threshold_low"
	// FieldDepositAmount holds the string denoting the deposit_amount field in the database.
	FieldDepositAmount = "deposit_amount"
	// FieldOnlineScale holds the string denoting the online_scale field in the database.
	FieldOnlineScale = "online_scale"
	// Table holds the table name of the coingas in the database.
	Table = "coin_gas"
)

// Columns holds all SQL columns for coingas fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCoinTypeID,
	FieldGasCoinTypeID,
	FieldDepositThresholdLow,
	FieldDepositAmount,
	FieldOnlineScale,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/NpoolPlatform/gas-feeder/pkg/db/ent/runtime"
//
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() uint32
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() uint32
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() uint32
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() uint32
	// DefaultOnlineScale holds the default value on creation for the "online_scale" field.
	DefaultOnlineScale int32
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
