// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CoinGas is the predicate function for coingas builders.
type CoinGas func(*sql.Selector)

// Deposit is the predicate function for deposit builders.
type Deposit func(*sql.Selector)
